/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package eu.sycomore.gmmv2.ircode01.wrapper;

public class IRCodeProducer_WrapperJNI {
  public final static native void delete_Pipo(long jarg1);

  static {
    try {
        System.loadLibrary("native-lib");
    } catch (UnsatisfiedLinkError e) {
      System.err.println("Native code library failed to load. \n" + e);
      System.exit(1);
    }
  }

}
